package config

import (
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// write writes a config file into a temp dir and returns its path.
func write(t *testing.T, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "anteroom.toml")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

const minimal = `upstream = "127.0.0.1:3000"` + "\n"

const paymentsHeader = `
[payments]
pay_to      = "0x000000000000000000000000000000000000dEaD"
facilitator = "https://facilitator.example"

[[payments.rails]]
network       = "eip155:72344"
asset         = "0xtoken"
asset_name    = "Stable Coin"
asset_version = "1"
asset_transfer_method = "permit2"
`

func TestLoadMinimal(t *testing.T) {
	cfg, err := Load(write(t, minimal))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	// Defaults hold.
	// ":8080" and not ":80": the default must bind as an ordinary user.
	if cfg.Listen != ":8080" || cfg.PassTTL.D() != 60*time.Second || cfg.MaxSession.D() != 30*time.Minute || cfg.ShutdownGrace.D() != 5*time.Second {
		t.Errorf("time defaults wrong: %+v", cfg)
	}
	if cfg.Difficulty != 14 || cfg.RenewDifficulty != 6 {
		t.Errorf("difficulty defaults wrong: %+v", cfg)
	}
	if !cfg.Inject || !cfg.Triage.JSONAccept {
		t.Error("inject/json_accept should default true")
	}
	// No admin listener unless asked for: it is unauthenticated, so silently
	// opening a port the operator never configured would be a surprise surface.
	if cfg.AdminListen != "" {
		t.Errorf("admin_listen should default off, got %q", cfg.AdminListen)
	}
	// A key was generated and flagged.
	if len(cfg.HMACKeys) != 1 || !cfg.KeyAutoGenerated {
		t.Errorf("auto key: %+v, flag %v", cfg.HMACKeys, cfg.KeyAutoGenerated)
	}
	keys, err := cfg.Keys()
	if err != nil || len(keys) != 1 || len(keys[0].Key) != 32 {
		t.Errorf("Keys() = %v, %v", keys, err)
	}
	u, err := cfg.UpstreamURL()
	if err != nil || u.String() != "http://127.0.0.1:3000" {
		t.Errorf("UpstreamURL = %v, %v", u, err)
	}
}

func TestLoadFullPayments(t *testing.T) {
	cfg, err := Load(write(t, minimal+paymentsHeader+`
[[payments.rules]]
name  = "site"
paths = ["/*"]
price = "$0.01"
paid_ttl = "1h"

[[payments.rules]]
name  = "reports"
paths = ["/reports/*"]
price = "2.50"
paid_ttl = "24h"
`))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	r := cfg.Payments.Rules
	const rail0 = "eip155:72344"
	if r[0].PriceAtomic[rail0].String() != "10000" { // $0.01 at 6 decimals
		t.Errorf("site price atomic = %s, want 10000", r[0].PriceAtomic[rail0])
	}
	if r[1].PriceAtomic[rail0].String() != "2500000" {
		t.Errorf("reports price atomic = %s, want 2500000", r[1].PriceAtomic[rail0])
	}
	rail := cfg.Payments.Rails[0]
	if rail.Decimals != 6 {
		t.Errorf("decimals default = %d", rail.Decimals)
	}
	if rail.AssetName != "Stable Coin" || rail.AssetVersion != "1" {
		t.Errorf("EIP-712 domain not loaded: %q/%q", rail.AssetName, rail.AssetVersion)
	}
	// pay_to falls through to the rail unless overridden.
	if rail.PayTo != "0x000000000000000000000000000000000000dEaD" {
		t.Errorf("rail pay_to = %q, want the payments-level address", rail.PayTo)
	}
	// maxTimeoutSeconds is a required wire field, so it needs a usable default.
	if cfg.Payments.MaxTimeoutSeconds != 300 {
		t.Errorf("max_timeout_seconds default = %d, want 300", cfg.Payments.MaxTimeoutSeconds)
	}
}

func TestPaymentStateFileResolvesFromConfig(t *testing.T) {
	paymentsWithState := strings.Replace(paymentsHeader,
		`facilitator = "https://facilitator.example"`,
		"facilitator = \"https://facilitator.example\"\nstate_file = \"state/payments.db\"", 1)
	path := write(t, minimal+paymentsWithState+`
[[payments.rules]]
name = "site"
paths = ["/*"]
price = "$0.01"
paid_ttl = "1h"
`)
	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	want := filepath.Join(filepath.Dir(path), "state", "payments.db")
	if cfg.Payments.StateFile != want {
		t.Fatalf("state_file = %q, want %q", cfg.Payments.StateFile, want)
	}

	path = write(t, minimal+paymentsHeader+`
[[payments.rules]]
name = "site"
paths = ["/*"]
price = "$0.01"
paid_ttl = "1h"
`)
	cfg, err = Load(path)
	if err != nil {
		t.Fatalf("Load default: %v", err)
	}
	want = filepath.Join(filepath.Dir(path), "anteroom-payments.db")
	if cfg.Payments.StateFile != want {
		t.Fatalf("default state_file = %q, want %q", cfg.Payments.StateFile, want)
	}
}

// TestMultipleRails: offering more than one way to pay is what makes a gate
// payable by a wallet that only holds funds on one chain — the client filters
// accepts[] to what it registered and pays the first survivor.
func TestMultipleRails(t *testing.T) {
	cfg, err := Load(write(t, minimal+`
[payments]
pay_to      = "0x000000000000000000000000000000000000dEaD"
facilitator = "https://f.example"

[[payments.rails]]
network       = "eip155:72344"
asset         = "0xsbc"
asset_name    = "Stable Coin"
asset_version = "1"
asset_transfer_method = "permit2"

[[payments.rails]]
network       = "eip155:8453"
asset         = "0xusdc"
decimals      = 6
asset_name    = "USD Coin"
asset_version = "2"
pay_to        = "0x000000000000000000000000000000000000BEEF"

[[payments.rules]]
name  = "site"
paths = ["/*"]
price = "$0.01"
paid_ttl = "1h"
`))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(cfg.Payments.Rails) != 2 {
		t.Fatalf("rails = %d, want 2", len(cfg.Payments.Rails))
	}
	// The same display price resolves once per rail.
	pa := cfg.Payments.Rules[0].PriceAtomic
	if pa["eip155:72344"].String() != "10000" || pa["eip155:8453"].String() != "10000" {
		t.Errorf("per-rail prices wrong: %v", pa)
	}
	// The second rail's transfer method defaults and its pay_to override wins.
	if cfg.Payments.Rails[1].AssetTransferMethod != "eip3009" {
		t.Errorf("rail 2 transfer method = %q", cfg.Payments.Rails[1].AssetTransferMethod)
	}
	if cfg.Payments.Rails[1].PayTo != "0x000000000000000000000000000000000000BEEF" {
		t.Errorf("rail 2 pay_to override ignored: %q", cfg.Payments.Rails[1].PayTo)
	}
}

func TestDecimalsAffectPricePerRail(t *testing.T) {
	cfg, err := Load(write(t, minimal+`
[payments]
pay_to      = "0x000000000000000000000000000000000000dEaD"
facilitator = "https://f.example"

[[payments.rails]]
network       = "eip155:1"
asset         = "0xsix"
decimals      = 6
asset_name    = "Six"
asset_version = "1"

[[payments.rails]]
network       = "eip155:2"
asset         = "0xeighteen"
decimals      = 18
asset_name    = "Eighteen"
asset_version = "1"

[[payments.rules]]
name  = "site"
paths = ["/*"]
price = "$1.50"
paid_ttl = "1h"
`))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	pa := cfg.Payments.Rules[0].PriceAtomic
	if pa["eip155:1"].String() != "1500000" {
		t.Errorf("6-decimal atomic = %s, want 1500000", pa["eip155:1"])
	}
	if pa["eip155:2"].String() != "1500000000000000000" {
		t.Errorf("18-decimal atomic = %s, want 1.5e18", pa["eip155:2"])
	}
}

func TestPermit2NeedsNoSpecialCasing(t *testing.T) {
	// Radius-style config: permit2 transfer method with an EIP-2612 domain.
	cfg, err := Load(write(t, minimal+paymentsHeader+`
[[payments.rules]]
name  = "site"
paths = ["/*"]
price = "$0.001"
paid_ttl = "1h"
`))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Payments.Rails[0].AssetTransferMethod != "permit2" {
		t.Errorf("transfer method = %q", cfg.Payments.Rails[0].AssetTransferMethod)
	}
}

// replaceKey rewrites `key = ...` in a TOML body regardless of column
// alignment, so tests do not break when the example config is reformatted.
func replaceKey(t *testing.T, body, key, value string) string {
	t.Helper()
	re := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(key) + `\s*=.*$`)
	// Literal: prices contain '$', which ReplaceAllString would read as a
	// capture-group reference.
	out := re.ReplaceAllLiteralString(body, key+" = "+value)
	if out == body {
		t.Fatalf("replaceKey: %q not found in body", key)
	}
	return out
}

func TestLoadRejects(t *testing.T) {
	rule := func(extra string) string {
		ttl := "paid_ttl = \"1h\"\n"
		if strings.Contains(extra, "paid_ttl") {
			ttl = ""
		}
		return minimal + paymentsHeader + `
[[payments.rules]]
name  = "site"
paths = ["/*"]
price = "$0.01"
` + ttl + extra
	}
	for _, tc := range []struct {
		name string
		body string
		want error  // nil = just any error
		msg  string // substring the error must carry (actionability)
	}{
		{"no upstream", `listen = ":80"`, ErrNoUpstream, "127.0.0.1:3000"},
		{"bad upstream", `upstream = "://nope"`, nil, "host:port"},
		{"unknown key", minimal + "upstrem = \"x\"\n", nil, "unknown key"},
		{"zero pass_ttl", minimal + `pass_ttl = "0s"`, ErrBadTTL, "at least 1s"},
		{"sub-second pass_ttl", minimal + `pass_ttl = "500ms"`, ErrBadTTL, "at least 1s"},
		{"bad duration", minimal + `pass_ttl = "ten seconds"`, nil, "duration"},
		{"max_session below pass_ttl", minimal + "pass_ttl = \"10m\"\nmax_session = \"1m\"\n", ErrBadTTL, "max_session"},
		{"zero shutdown grace", minimal + "shutdown_grace = \"0s\"\n", nil, "between 1s and 1h"},
		{"excessive shutdown grace", minimal + "shutdown_grace = \"2h\"\n", nil, "between 1s and 1h"},
		{"wildcard public host", minimal + "public_hosts = [\"*.example.com\"]\n", nil, "exact host"},
		{"URL as public host", minimal + "public_hosts = [\"https://example.com\"]\n", nil, "exact host"},
		{"difficulty range", minimal + `difficulty = 300`, ErrBadDifficulty, "255"},
		{"difficulty zero fails open", minimal + `difficulty = 0`, ErrBadDifficulty, "costs an attacker nothing"},
		{"renew above admission", minimal + "difficulty = 8\nrenew_difficulty = 16\n", ErrBadDifficulty, "cheaper"},
		{"reserved rule name", minimal + paymentsHeader + "[[payments.rules]]\nname = \"*\"\npaths = [\"/x\"]\nprice = \"$1\"\n", nil, "reserved"},
		{"bad hmac key", minimal + "[[hmac_keys]]\nkid = \"k\"\nkey = \"!!\"\n", ErrBadKey, "openssl rand"},
		{"hmac key no kid", minimal + "[[hmac_keys]]\nkey = \"MDEyMzQ1Njc4OWFiY2RlZg==\"\n", ErrBadKey, "kid"},
		{"bad bypass cidr", minimal + "[bypass]\ncidrs = [\"nope\"]\n", nil, "cidr"},
		{"bad trusted proxy", minimal + `trusted_proxies = ["512.0.0.1"]`, nil, "trusted_proxies"},
		{"bad admin_listen", minimal + `admin_listen = "8090"`, nil, "host:port"},
		{"admin_listen same as listen", minimal + "listen = \":8080\"\nadmin_listen = \":8080\"\n", nil, "same address"},
		{"payments no pay_to", minimal + "[payments]\nfacilitator = \"https://f\"\n[[payments.rails]]\nnetwork = \"eip155:1\"\nasset = \"0x\"\nasset_name = \"T\"\nasset_version = \"1\"\n[[payments.rules]]\nname=\"s\"\npaths=[\"/*\"]\nprice=\"$1\"\n", ErrNoPayTo, "cast wallet new"},
		{"payments no rules", minimal + paymentsHeader, ErrNoRules, "payments.rules"},
		{"network not caip2", replaceKey(t, rule(""), "network", `"radius"`), nil, "CAIP-2"},
		{"zero price", replaceKey(t, rule(""), "price", `"$0.00"`), ErrBadPrice, "zero"},
		{"removed grant key", rule("grant = \"session\"\n"), nil, "unknown key"},
		{"removed scheme key", rule("scheme = \"exact\"\n"), nil, "unknown key"},
		{"removed challenge key", rule("challenge = \"pow-sha256\"\n"), nil, "unknown key"},
		{"duplicate rule name", rule("") + "\n[[payments.rules]]\nname = \"site\"\npaths = [\"/x\"]\nprice = \"$1\"\n", nil, "unique"},
		{"rule no paths", minimal + paymentsHeader + "[[payments.rules]]\nname = \"site\"\nprice = \"$1\"\n", nil, "paths"},
		{"zero paid_ttl", rule("paid_ttl = \"0s\"\n"), ErrBadTTL, "at least 1s"},
		{"negative paid_ttl", rule("paid_ttl = \"-1s\"\n"), ErrBadTTL, "at least 1s"},
		{"pages dir missing files", minimal + "pages = \"" + os.TempDir() + "\"", nil, "header.html"},
		// The token's EIP-712 domain is required by the x402 `exact` scheme;
		// omitting it produces a facilitator error no operator can decode.
		{"no asset_name", replaceKey(t, rule(""), "asset_name", `""`), nil, "EIP-712 domain"},
		{"no asset_version", replaceKey(t, rule(""), "asset_version", `""`), nil, "EIP-712 domain"},
		{"bad transfer method", minimal + replaceKey(t, paymentsHeader, "asset_transfer_method", `"magic"`) + "[[payments.rules]]\nname = \"s\"\npaths = [\"/*\"]\nprice = \"$1\"\n", nil, "eip3009"},
		{"erc7710 rejected with reason", minimal + replaceKey(t, paymentsHeader, "asset_transfer_method", `"erc7710"`) + "[[payments.rules]]\nname = \"s\"\npaths = [\"/*\"]\nprice = \"$1\"\n", nil, "no shipped client implements it"},
		{"removed v1_network key", minimal + paymentsHeader + "v1_network = \"base\"\n[[payments.rules]]\nname = \"s\"\npaths = [\"/*\"]\nprice = \"$1\"\n", nil, "unknown key"},
		{"max_timeout out of range", minimal + "[payments]\npay_to=\"0x000000000000000000000000000000000000dEaD\"\nfacilitator=\"https://f\"\nmax_timeout_seconds = 99999\n[[payments.rails]]\nnetwork=\"eip155:1\"\nasset=\"0x\"\nasset_name=\"T\"\nasset_version=\"1\"\n[[payments.rules]]\nname = \"s\"\npaths = [\"/*\"]\nprice = \"$1\"\n", nil, "max_timeout_seconds"},
		{"activity ttl too short", minimal + "[activity]\nttl = \"1s\"\n", nil, "activity.ttl"},
		{"activity ttl too long", minimal + "[activity]\nttl = \"48h\"\n", nil, "activity.ttl"},
		{"activity max_ips out of range", minimal + "[activity]\nmax_ips = 5000000\n", nil, "activity.max_ips"},
		{"activity unknown key", minimal + "[activity]\nttls = \"10m\"\n", nil, "unknown key"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Load(write(t, tc.body))
			if err == nil {
				t.Fatal("Load accepted bad config")
			}
			if tc.want != nil && !errors.Is(err, tc.want) {
				t.Fatalf("err = %v, want %v", err, tc.want)
			}
			if !strings.Contains(strings.ToLower(err.Error()), strings.ToLower(tc.msg)) {
				t.Fatalf("error not actionable: %q lacks %q", err, tc.msg)
			}
		})
	}
}

// TestActivitySection pins the optional-section contract: absent means nil
// (no per-visitor state anywhere), present-but-empty means the documented
// defaults, and explicit values stick.
func TestActivitySection(t *testing.T) {
	cfg, err := Load(write(t, minimal))
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Activity != nil {
		t.Fatalf("activity should default off, got %+v", cfg.Activity)
	}

	cfg, err = Load(write(t, minimal+"[activity]\n"))
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Activity == nil || cfg.Activity.TTL.D() != 10*time.Minute || cfg.Activity.MaxIPs != 8192 {
		t.Fatalf("empty section defaults wrong: %+v", cfg.Activity)
	}

	cfg, err = Load(write(t, minimal+"[activity]\nttl = \"30m\"\nmax_ips = 100\n"))
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Activity.TTL.D() != 30*time.Minute || cfg.Activity.MaxIPs != 100 {
		t.Fatalf("explicit values not honored: %+v", cfg.Activity)
	}
}

func TestEnvOverrides(t *testing.T) {
	t.Setenv("ANTEROOM_LISTEN", "127.0.0.1:9999")
	t.Setenv("ANTEROOM_ADMIN_LISTEN", "127.0.0.1:9998")
	t.Setenv("ANTEROOM_UPSTREAM", "127.0.0.1:4000")
	t.Setenv("ANTEROOM_HMAC_KEY", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=")
	cfg, err := Load(write(t, minimal))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Listen != "127.0.0.1:9999" || cfg.Upstream != "127.0.0.1:4000" {
		t.Errorf("env overrides not applied: %+v", cfg)
	}
	if cfg.AdminListen != "127.0.0.1:9998" {
		t.Errorf("ANTEROOM_ADMIN_LISTEN not applied: %q", cfg.AdminListen)
	}
	if cfg.KeyAutoGenerated || cfg.HMACKeys[0].Kid != "env" {
		t.Errorf("env key not used: %+v", cfg.HMACKeys)
	}
}

func TestParsePrice(t *testing.T) {
	for _, tc := range []struct {
		price    string
		decimals int
		want     string // "" = error
	}{
		{"$0.01", 6, "10000"},
		{"0.01", 6, "10000"},
		{" $2.50 ", 6, "2500000"},
		{"1", 6, "1000000"},
		{"0.000001", 6, "1"},
		{".5", 6, "500000"},
		{"3.", 6, "3000000"},
		{"$0.001", 2, ""},   // more digits than decimals
		{"0", 6, ""},        // zero
		{"0.000000", 6, ""}, // zero
		{"", 6, ""},
		{"$", 6, ""},
		{".", 6, ""},
		{"-1", 6, ""},
		{"1e6", 6, ""},
		{"0x10", 6, ""},
		{"1,50", 6, ""},
	} {
		got, err := parsePrice(tc.price, tc.decimals)
		if tc.want == "" {
			if err == nil {
				t.Errorf("parsePrice(%q) accepted, got %s", tc.price, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("parsePrice(%q): %v", tc.price, err)
			continue
		}
		if got.String() != tc.want {
			t.Errorf("parsePrice(%q) = %s, want %s", tc.price, got, tc.want)
		}
	}
}

func TestPagesDirValidated(t *testing.T) {
	dir := t.TempDir()
	for _, f := range []string{"header.html", "footer.html"} {
		if err := os.WriteFile(filepath.Join(dir, f), []byte("<html>"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := Load(write(t, minimal+"pages = \""+dir+"\"\n")); err != nil {
		t.Fatalf("Load with complete pages dir: %v", err)
	}
}

// TestUpstreamSocket pins the unix-socket forms. Application servers bound to a
// socket rather than a port are ordinary — gunicorn, puma, uwsgi and php-fpm
// all default that way in common packaging — and the alternative to supporting
// them is asking an operator to reconfigure someone else's service to
// accommodate the gate.
func TestUpstreamSocket(t *testing.T) {
	tests := []struct {
		upstream string
		want     string
	}{
		{"unix:/run/app.sock", "/run/app.sock"},
		{"unix:///run/app.sock", "/run/app.sock"},
		{"unix:/var/run/php/php8.4-fpm.sock", "/var/run/php/php8.4-fpm.sock"},

		// Not sockets: these must keep their existing meaning exactly.
		{"127.0.0.1:3000", ""},
		{"http://127.0.0.1:3000", ""},
		{"https://app.internal", ""},
		{"app:3000", ""},

		// Malformed: a relative path is not a socket we will dial, and must not
		// be silently treated as one.
		{"unix:relative/path.sock", ""},
		{"unix:", ""},
		{"unix://", ""},
	}
	for _, tt := range tests {
		t.Run(tt.upstream, func(t *testing.T) {
			c := &Config{Upstream: tt.upstream}
			if got := c.UpstreamSocket(); got != tt.want {
				t.Errorf("UpstreamSocket(%q) = %q, want %q", tt.upstream, got, tt.want)
			}
		})
	}
}

// TestUpstreamURLWithSocket checks that a socket upstream still yields a usable
// URL. The reverse proxy needs one to build a request line even though the host
// never reaches the wire.
func TestUpstreamURLWithSocket(t *testing.T) {
	c := &Config{Upstream: "unix:/run/app.sock"}
	u, err := c.UpstreamURL()
	if err != nil {
		t.Fatalf("UpstreamURL: %v", err)
	}
	if u.Scheme != "http" || u.Host == "" {
		t.Errorf("UpstreamURL = %+v, want an http URL with a placeholder host", u)
	}
}

// TestUpstreamErrorNamesTheSocketForm. A config error is only useful if it says
// what the accepted spellings are.
func TestUpstreamErrorNamesTheSocketForm(t *testing.T) {
	c := &Config{Upstream: "ftp://nope"}
	_, err := c.UpstreamURL()
	if err == nil {
		t.Fatal("accepted an ftp upstream")
	}
	if !strings.Contains(err.Error(), "unix:") {
		t.Errorf("error does not mention the unix form: %v", err)
	}
}

// TestPerRailFacilitator covers the per-rail facilitator override: the same
// URL hardening as the global key, credentials arriving via headers + env, and
// the all-or-nothing inheritance rule (a rail with its own facilitator must
// not inherit the global credential — that would aim one facilitator's key at
// another facilitator's host).
func TestPerRailFacilitator(t *testing.T) {
	const good = "0x000000000000000000000000000000000000dEaD"
	base := func(railExtra, paymentsExtra string) string {
		return "upstream = \"127.0.0.1:3000\"\n[payments]\npay_to=\"" + good +
			"\"\nfacilitator=\"https://global.example\"\n" + paymentsExtra +
			"[[payments.rails]]\nnetwork=\"eip155:1\"\nasset=\"0xa\"\n" +
			"asset_name=\"T\"\nasset_version=\"1\"\n" + railExtra +
			"[[payments.rules]]\nname=\"s\"\npaths=[\"/*\"]\nprice=\"$1\"\npaid_ttl=\"1h\"\n"
	}
	load := func(t *testing.T, body string) (*Config, error) {
		t.Helper()
		path := filepath.Join(t.TempDir(), "anteroom.toml")
		if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
		return Load(path)
	}

	t.Run("inherits URL and headers as a unit", func(t *testing.T) {
		t.Setenv("TEST_FAC_KEY", "sekrit")
		cfg, err := load(t, base("", "facilitator_headers=[\"Authorization: Bearer ${TEST_FAC_KEY}\"]\n"))
		if err != nil {
			t.Fatal(err)
		}
		rl := cfg.Payments.Rails[0]
		if rl.Facilitator != "https://global.example" {
			t.Errorf("facilitator = %q, want the global", rl.Facilitator)
		}
		if got := rl.FacilitatorHeader.Get("Authorization"); got != "Bearer sekrit" {
			t.Errorf("Authorization = %q, want the expanded global header", got)
		}
	})

	t.Run("own facilitator does not inherit global headers", func(t *testing.T) {
		cfg, err := load(t, base("facilitator=\"https://own.example\"\n",
			"facilitator_headers=[\"Authorization: Bearer globalkey\"]\n"))
		if err != nil {
			t.Fatal(err)
		}
		rl := cfg.Payments.Rails[0]
		if rl.Facilitator != "https://own.example" {
			t.Errorf("facilitator = %q", rl.Facilitator)
		}
		if got := rl.FacilitatorHeader.Get("Authorization"); got != "" {
			t.Errorf("a rail with its own facilitator inherited the global credential: %q", got)
		}
	})

	t.Run("own headers expand and parse", func(t *testing.T) {
		t.Setenv("TEST_RAIL_KEY", "abc123")
		cfg, err := load(t, base("facilitator=\"https://own.example\"\n"+
			"facilitator_headers=[\"Authorization: Bearer ${TEST_RAIL_KEY}\"]\n", ""))
		if err != nil {
			t.Fatal(err)
		}
		if got := cfg.Payments.Rails[0].FacilitatorHeader.Get("Authorization"); got != "Bearer abc123" {
			t.Errorf("Authorization = %q", got)
		}
	})

	rejects := []struct {
		name      string
		railExtra string
		payExtra  string
		wantErr   string
	}{
		{"per-rail plaintext non-loopback", "facilitator=\"http://f.example\"\n", "", "plaintext http"},
		{"per-rail non-http scheme", "facilitator=\"unix:/tmp/f\"\n", "", "not an http(s) URL"},
		{"userinfo in per-rail URL", "facilitator=\"https://user:key@f.example\"\n", "", "credentials in the URL"},
		{"userinfo in global URL is caught too", "", "", ""}, // handled below
		{"headers without facilitator", "facilitator_headers=[\"Authorization: Bearer k\"]\n", "", "without facilitator"},
		{"header missing colon", "facilitator=\"https://f.example\"\nfacilitator_headers=[\"NoColonHere\"]\n", "", "Name: value"},
		{"header empty name", "facilitator=\"https://f.example\"\nfacilitator_headers=[\": v\"]\n", "", "Name: value"},
		{"reserved header rejected case-insensitively", "facilitator=\"https://f.example\"\nfacilitator_headers=[\"content-type: x\"]\n", "", "owned by the gate"},
		{"invalid header name", "facilitator=\"https://f.example\"\nfacilitator_headers=[\"Bad Name: x\"]\n", "", "not a valid HTTP header name"},
		{"unset env var named in error", "facilitator=\"https://f.example\"\nfacilitator_headers=[\"Authorization: Bearer ${TEST_DEFINITELY_UNSET_VAR}\"]\n", "", "TEST_DEFINITELY_UNSET_VAR"},
	}
	for _, tt := range rejects {
		if tt.name == "userinfo in global URL is caught too" {
			continue
		}
		t.Run(tt.name, func(t *testing.T) {
			_, err := load(t, base(tt.railExtra, tt.payExtra))
			if err == nil {
				t.Fatalf("accepted %s", tt.name)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("error %q does not mention %q", err, tt.wantErr)
			}
		})
	}

	t.Run("per-rail loopback may be plaintext", func(t *testing.T) {
		if _, err := load(t, base("facilitator=\"http://127.0.0.1:9\"\n", "")); err != nil {
			t.Fatalf("rejected loopback plaintext per-rail facilitator: %v", err)
		}
	})

	t.Run("userinfo in the global URL", func(t *testing.T) {
		body := "upstream = \"127.0.0.1:3000\"\n[payments]\npay_to=\"" + good +
			"\"\nfacilitator=\"https://user:key@f.example\"\n" +
			"[[payments.rails]]\nnetwork=\"eip155:1\"\nasset=\"0xa\"\n" +
			"asset_name=\"T\"\nasset_version=\"1\"\n" +
			"[[payments.rules]]\nname=\"s\"\npaths=[\"/*\"]\nprice=\"$1\"\n"
		_, err := load(t, body)
		if err == nil || !strings.Contains(err.Error(), "credentials in the URL") {
			t.Errorf("global userinfo not rejected: %v", err)
		}
	})
}

// TestPayToAndFacilitatorHardening covers two config checks that exist because
// getting them wrong is silent and expensive.
func TestPayToAndFacilitatorHardening(t *testing.T) {
	const rails = "[[payments.rails]]\nnetwork=\"eip155:1\"\nasset=\"0xa\"\n" +
		"asset_name=\"T\"\nasset_version=\"1\"\n" +
		"[[payments.rules]]\nname=\"s\"\npaths=[\"/*\"]\nprice=\"$1\"\npaid_ttl=\"1h\"\n"
	const good = "0x000000000000000000000000000000000000dEaD"

	tests := []struct {
		name    string
		payTo   string
		facil   string
		wantErr string
	}{
		{"valid", good, "https://f.example", ""},
		{
			// A typo here advertises a recipient nobody controls, and every
			// payment made against the offer is lost. Nothing fails loudly at
			// runtime, so the config is the only place to catch it.
			name: "pay_to is not an address", payTo: "0xnope", facil: "https://f.example",
			wantErr: "not an EVM address",
		},
		{
			// Settlement verdicts decide whether content is served, so a forged
			// response over an unencrypted link is free access to paid content.
			name: "plaintext facilitator", payTo: good, facil: "http://f.example",
			wantErr: "plaintext http",
		},
		{"loopback may be plaintext", good, "http://127.0.0.1:8080", ""},
		{"localhost may be plaintext", good, "http://localhost:8080", ""},
		// The near misses, which are the rows that make the two above mean
		// something. Without them, loosening isLoopbackHost to a suffix or
		// prefix match — the natural "be helpful about hostnames" edit — passes
		// every accepting row, and an attacker-controlled host then qualifies as
		// loopback and gets to answer settlement verdicts over plaintext.
		{"a host that merely ends in localhost is not loopback", good,
			"http://localhost.attacker.example:8080", "plaintext http"},
		{"a host that merely starts with localhost is not loopback", good,
			"http://localhosts.example:8080", "plaintext http"},
		{"a public address in the 127 text is not loopback", good,
			"http://127.0.0.1.attacker.example:8080", "plaintext http"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			body := "upstream = \"127.0.0.1:3000\"\n[payments]\npay_to=\"" + tt.payTo +
				"\"\nfacilitator=\"" + tt.facil + "\"\n" + rails
			path := filepath.Join(t.TempDir(), "anteroom.toml")
			if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
				t.Fatal(err)
			}
			_, err := Load(path)
			if tt.wantErr == "" {
				if err != nil {
					t.Fatalf("rejected a valid config: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatalf("accepted %s", tt.name)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("error %q does not mention %q", err, tt.wantErr)
			}
		})
	}
}
