// Package config loads and validates anteroom.toml — the public contract.
//
// Validation is strict and errors are actionable: a config mistake should be a
// one-glance fix, naming the key, the problem, and the likely correction.
package config

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"math/big"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/BurntSushi/toml"

	"github.com/radiustechsystems/anteroom/internal/bypass"
	"github.com/radiustechsystems/anteroom/internal/token"
)

// Sentinel errors for validation; wrapped with context at the failure site.
var (
	ErrNoUpstream    = errors.New("config: upstream is required")
	ErrNoPayTo       = errors.New("config: payments.pay_to is required")
	ErrNoRules       = errors.New("config: payments needs at least one [[payments.rules]]")
	ErrBadPrice      = errors.New("config: bad price")
	ErrBadKey        = errors.New("config: bad hmac key")
	ErrBadDifficulty = errors.New("config: bad difficulty")
	ErrBadTTL        = errors.New("config: bad ttl")
)

// minDifficulty is the floor for admission work. Below a handful of bits the
// puzzle is free for an attacker while still costing honest visitors a round
// trip, so it is a misconfiguration rather than a lenient setting.
const minDifficulty = 4

// Duration is a time.Duration that unmarshals from TOML strings like "10s".
type Duration time.Duration

func (d *Duration) UnmarshalText(b []byte) error {
	v, err := time.ParseDuration(string(b))
	if err != nil {
		return err
	}
	*d = Duration(v)
	return nil
}

func (d Duration) D() time.Duration { return time.Duration(d) }

// Config mirrors anteroom.example.toml. Optional sections are pointers.
type Config struct {
	Listen string `toml:"listen"`

	// AdminListen is the metrics/health listener (/metrics, /stats, /healthz).
	// Empty (the default) means no admin listener at all. It is deliberately a
	// separate port from the gate: the admin surface is unauthenticated, so
	// reachability is the entire access control — bind it to loopback or a
	// private interface, never the gate's public address.
	AdminListen     string   `toml:"admin_listen"`
	Upstream        string   `toml:"upstream"`
	PassTTL         Duration `toml:"pass_ttl"`
	MaxSession      Duration `toml:"max_session"`
	ShutdownGrace   Duration `toml:"shutdown_grace"`
	Difficulty      float64  `toml:"difficulty"`
	RenewDifficulty float64  `toml:"renew_difficulty"`
	Pages           string   `toml:"pages"`
	Inject          bool     `toml:"inject"`

	// AllowInsecureContext ships a JavaScript SHA-256 fallback so the gate works
	// where WebCrypto is unavailable — which means any page not served over
	// HTTPS or from localhost, e.g. a Docker deployment reached at
	// http://192.168.x.y. Off by default because the fallback is 10-50x slower
	// per hash than WebCrypto, and that gap is pure loss for the honest visitor:
	// an attacker's native implementation is unaffected. Reasonable on a LAN or
	// in development; a downgrade on the public internet. Note that service
	// workers also require a secure context, so in this mode there is no
	// background renewal; the visitor solves again after the pass lapses.
	AllowInsecureContext bool      `toml:"allow_insecure_context"`
	PublicHosts          []string  `toml:"public_hosts"`
	TrustedProxies       []string  `toml:"trusted_proxies"`
	HMACKeys             []HMACKey `toml:"hmac_keys"`
	Payments             *Payments `toml:"payments"`
	Activity             *Activity `toml:"activity"`
	Bypass               Bypass    `toml:"bypass"`
	Triage               Triage    `toml:"triage"`

	// KeyAutoGenerated is set when no hmac_keys were configured and one was
	// generated for this process. Fleets must not rely on it: every restart
	// invalidates all passes, and no other instance can verify them.
	KeyAutoGenerated bool `toml:"-"`
}

type HMACKey struct {
	Kid string `toml:"kid"`
	Key string `toml:"key"` // base64 (std or url, padded or not)
}

type Payments struct {
	PayTo       string `toml:"pay_to"`
	Facilitator string `toml:"facilitator"`
	// StateFile holds durable payment-to-grant records. Relative paths are
	// resolved from the configuration file, so the default lives beside it.
	StateFile string `toml:"state_file"`

	// FacilitatorHeaders are extra headers sent on every call to the default
	// facilitator, "Name: value" per entry, with ${VAR} expanded from the
	// environment at load — the same route ANTEROOM_HMAC_KEY takes: the secret
	// lives in the process environment, not in a file that gets copied around.
	// An unset variable refuses to start; a facilitator that needs an API key
	// and silently doesn't send one fails on every settlement, which is a
	// worse place to discover the typo.
	FacilitatorHeaders []string `toml:"facilitator_headers"`

	// MaxTimeoutSeconds is echoed into PaymentRequirements, where it is a
	// required field: how long the gate will wait for a payment to be
	// presented and settled. Sized so ordinary clock skew never invalidates an
	// honest fresh payment.
	MaxTimeoutSeconds int `toml:"max_timeout_seconds"`

	// ResourceDescription is advertised in PaymentRequired.resource, which the
	// spec marks required. Purely descriptive; it tells an agent what it is
	// buying.
	ResourceDescription string `toml:"resource_description"`

	// Rails are the ways a client may pay, advertised as one accepts[] entry
	// each. Offering more than one matters in practice: an x402 client filters
	// accepts[] down to the networks and schemes its wallet actually registered
	// and pays the first survivor, so a client whose wallet only holds funds on
	// one chain silently picks that rail instead of failing. A gate offering a
	// single exotic rail is unpayable by most wallets, however conformant it is.
	Rails []Rail `toml:"rails"`

	Rules []Rule `toml:"rules"`
}

// Rail is one (network, asset) a payment may arrive on.
type Rail struct {
	Network  string `toml:"network"` // CAIP-2, e.g. "eip155:8453"
	Asset    string `toml:"asset"`   // token contract
	Decimals int    `toml:"decimals"`

	// AssetName and AssetVersion are the token contract's EIP-712 domain,
	// advertised in extra as `name`/`version`. The `exact` scheme requires them:
	// the reference client throws outright when they are missing, because it
	// cannot construct the transfer signature without them. They describe the
	// operator's token, so the operator supplies them and the gate needs no
	// chain access.
	AssetName    string `toml:"asset_name"`
	AssetVersion string `toml:"asset_version"`

	// AssetTransferMethod is advertised as extra.assetTransferMethod:
	// "eip3009" (the scheme default; USDC on Base) or "permit2" (Radius SBC).
	// The spec also names "erc7710", but no shipped client implements it, so
	// configuring it would produce an offer nothing can pay.
	AssetTransferMethod string `toml:"asset_transfer_method"`

	// PayTo overrides payments.pay_to for this rail, for chains where the
	// operator's address differs.
	PayTo string `toml:"pay_to"`

	// RPCURL is an optional public JSON-RPC endpoint for this rail's chain,
	// advertised to payers. The gate never calls it — invariant 1 forbids a
	// chain RPC client and that is unchanged; this is a string the operator
	// publishes so a payer does not have to guess.
	//
	// It earns its place empirically. An agent given everything else in the
	// offer still spent the largest single chunk of its time hunting an RPC
	// URL, and only succeeded because the chain happened to be in viem's
	// bundled registry. A CAIP-2 identifier names a chain; it does not tell you
	// where to reach one.
	RPCURL string `toml:"rpc_url"`

	// Facilitator overrides payments.facilitator for this rail — the same
	// shape as the PayTo override above, for the same reason: the operator who
	// settles Radius through their own facilitator and Base through Coinbase's
	// has two facilitators, and which one is called is a per-rail fact. Unlike
	// RPCURL this is a URL the gate DOES call; it gets the same https-or-
	// loopback hardening as the global key.
	//
	// Inheritance is all-or-nothing: a rail with no facilitator inherits the
	// global URL and the global headers; a rail with its own facilitator gets
	// only its own headers. Splitting them would send one facilitator's
	// credential to another facilitator's host.
	Facilitator        string   `toml:"facilitator"`
	FacilitatorHeaders []string `toml:"facilitator_headers"`

	// FacilitatorHeader is FacilitatorHeaders parsed and env-expanded at load
	// (or the global set, when this rail inherits). Same trick as
	// Rule.PriceAtomic: resolve once here so no downstream reader re-implements
	// the fallback.
	FacilitatorHeader http.Header `toml:"-"`
}

// transferMethods are the values a shipped x402 client can actually sign.
// "erc7710" is in the spec but unimplemented, so it is rejected rather than
// advertised into a dead end.
var transferMethods = map[string]bool{"eip3009": true, "permit2": true}

type Rule struct {
	Name    string   `toml:"name"`
	Paths   []string `toml:"paths"`
	Price   string   `toml:"price"`
	PaidTTL Duration `toml:"paid_ttl"`

	// PriceAtomic is Price resolved to atomic units per rail, keyed by the
	// rail's CAIP-2 network — the same display price can mean different atomic
	// amounts on assets with different decimals.
	PriceAtomic map[string]*big.Int `toml:"-"`
}

type Bypass struct {
	Paths []string `toml:"paths"`
	CIDRs []string `toml:"cidrs"`
}

// Activity turns on the per-IP challenge-activity log served at the admin
// endpoint /activity. Omitting the section (the default) keeps the gate fully
// free of per-visitor state; nothing else in anteroom records an address.
type Activity struct {
	// TTL is how long an IP stays listed after its last challenge activity.
	// It is the contract with the polling tool: entries can be up to this
	// stale, so poll faster than it.
	TTL Duration `toml:"ttl"`
	// MaxIPs bounds the tracked set against address-spraying. Past the cap
	// the quietest IP is evicted first.
	MaxIPs int `toml:"max_ips"`
}

// validate fills the section's defaults and rejects values whose consequences
// an operator would only discover in production.
func (a *Activity) validate() error {
	if a.TTL == 0 {
		a.TTL = Duration(10 * time.Minute)
	}
	if a.TTL.D() < 10*time.Second || a.TTL.D() > 24*time.Hour {
		return fmt.Errorf("config: activity.ttl %s outside [10s, 24h] — the ttl is how long a quiet IP stays visible to your polling tool; poll faster than it, e.g. ttl = \"10m\"", a.TTL.D())
	}
	if a.MaxIPs == 0 {
		a.MaxIPs = 8192
	}
	if a.MaxIPs < 16 || a.MaxIPs > 1_000_000 {
		return fmt.Errorf("config: activity.max_ips %d outside [16, 1000000] — each tracked IP costs ~100 bytes of memory; the default 8192 suits most sites", a.MaxIPs)
	}
	return nil
}

type Triage struct {
	JSONAccept   bool     `toml:"json_accept"`
	OKBodyAgents []string `toml:"ok_body_agents"`
}

// defaults returns a Config carrying every default the contract documents.
func defaults() Config {
	return Config{
		// 8080, not 80: ports below 1024 need root or CAP_NET_BIND_SERVICE on
		// Linux, and the documented topology puts a TLS terminator in front
		// anyway (WebCrypto needs a secure context, which Anteroom does not
		// provide itself). A default that cannot bind as an ordinary user is a
		// default that fails on first run.
		Listen: ":8080",
		// 60s, not 10s: renewal only runs while a driver page is open, and until
		// HTML injection ships that means only the wait page. A 10s pass walls a
		// visitor on nearly every click. It is also the solve deadline, and at
		// difficulty 16 a slow phone can legitimately need several seconds.
		PassTTL:    Duration(60 * time.Second),
		MaxSession: Duration(30 * time.Minute),
		// Long streams may need more; keep the default inside Docker's usual
		// ten-second stop budget and let deployments raise both together.
		ShutdownGrace: Duration(5 * time.Second),
		// 14 bits ≈ 16k WebCrypto hashes: about a second on a laptop, a few on
		// an old phone. Raise under attack; this is the operator's dial.
		Difficulty:      14,
		RenewDifficulty: 6,
		Inject:          true,
		Triage: Triage{
			JSONAccept: true,
			// Some agentic fetch tools discard the body of any non-2xx
			// response, so a 401 carrying instructions is invisible to them —
			// measured behavior, not a guess. For those clients the
			// instructions are served with status 200 instead, which is the
			// only way they see anything at all. Matched case-insensitively as
			// a substring of the User-Agent.
			OKBodyAgents: []string{"claude-user"},
		},
	}
}

// Load reads path, applies ANTEROOM_* environment overrides, validates, and
// resolves derived fields (price → atomic units, auto key generation).
func Load(path string) (*Config, error) {
	cfg := defaults()
	meta, err := toml.DecodeFile(path, &cfg)
	if err != nil {
		return nil, fmt.Errorf("config: %s: %w", path, err)
	}
	if un := meta.Undecoded(); len(un) > 0 {
		// Unknown keys are errors: a typo silently reverting to a default is
		// exactly the failure mode a security tool must not have.
		return nil, fmt.Errorf("config: %s: unknown key(s) %v — check spelling against anteroom.example.toml", path, un)
	}
	applyEnv(&cfg)
	if cfg.Payments != nil {
		configPath, absErr := filepath.Abs(path)
		if absErr != nil {
			return nil, fmt.Errorf("config: resolve %s: %w", path, absErr)
		}
		if cfg.Payments.StateFile == "" {
			cfg.Payments.StateFile = filepath.Join(filepath.Dir(configPath), "anteroom-payments.db")
		} else if !filepath.IsAbs(cfg.Payments.StateFile) {
			cfg.Payments.StateFile = filepath.Join(filepath.Dir(configPath), cfg.Payments.StateFile)
		}
	}
	if err := cfg.validate(); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// applyEnv layers documented environment overrides over the file.
func applyEnv(cfg *Config) {
	if v := os.Getenv("ANTEROOM_LISTEN"); v != "" {
		cfg.Listen = v
	}
	if v := os.Getenv("ANTEROOM_ADMIN_LISTEN"); v != "" {
		cfg.AdminListen = v
	}
	if v := os.Getenv("ANTEROOM_UPSTREAM"); v != "" {
		cfg.Upstream = v
	}
	if v := os.Getenv("ANTEROOM_PAGES"); v != "" {
		cfg.Pages = v
	}
	if v := os.Getenv("ANTEROOM_HMAC_KEY"); v != "" {
		cfg.HMACKeys = []HMACKey{{Kid: "env", Key: v}}
	}
}

func (c *Config) validate() error {
	if c.AdminListen != "" {
		if _, _, err := net.SplitHostPort(c.AdminListen); err != nil {
			return fmt.Errorf("config: admin_listen %q is not host:port — e.g. admin_listen = \"127.0.0.1:8090\", or omit it to run without the admin server", c.AdminListen)
		}
		// Same address as the gate fails eventually with "address already in
		// use"; failing here names the actual mistake.
		if c.AdminListen == c.Listen {
			return fmt.Errorf("config: admin_listen %q is the same address as listen — the admin server is unauthenticated and must not share the gate's port", c.AdminListen)
		}
	}
	if c.Upstream == "" {
		return fmt.Errorf("%w — point it at your real web server, e.g. upstream = \"127.0.0.1:3000\"", ErrNoUpstream)
	}
	if _, err := c.UpstreamURL(); err != nil {
		return err
	}
	if c.PassTTL.D() < time.Second {
		return fmt.Errorf("%w: pass_ttl must be at least 1s, got %s — it is also the solve deadline, and a browser needs time to work", ErrBadTTL, c.PassTTL.D())
	}
	if c.MaxSession.D() < c.PassTTL.D() {
		return fmt.Errorf("%w: max_session (%s) must be at least pass_ttl (%s)", ErrBadTTL, c.MaxSession.D(), c.PassTTL.D())
	}
	if c.ShutdownGrace.D() < time.Second || c.ShutdownGrace.D() > time.Hour {
		return fmt.Errorf("config: shutdown_grace must be between 1s and 1h, got %s", c.ShutdownGrace.D())
	}
	for _, authority := range c.PublicHosts {
		if authority == "" || authority != strings.TrimSpace(authority) ||
			strings.ContainsAny(authority, "/?#@") || strings.Contains(authority, "*") {
			return fmt.Errorf("config: public_hosts entry %q must be an exact host or host:port, without scheme, path, userinfo, or wildcard", authority)
		}
	}
	// A zero difficulty accepts any hash — a gate that gates nothing. Refuse it
	// rather than fail open silently.
	if c.Difficulty < minDifficulty || c.Difficulty > 255 {
		return fmt.Errorf("%w: difficulty %v outside [%v, 255] — below %v the puzzle costs an attacker nothing", ErrBadDifficulty, c.Difficulty, minDifficulty, minDifficulty)
	}
	if c.RenewDifficulty < 0 || c.RenewDifficulty > 255 {
		return fmt.Errorf("%w: renew_difficulty %v outside [0, 255]", ErrBadDifficulty, c.RenewDifficulty)
	}
	if c.RenewDifficulty > c.Difficulty {
		return fmt.Errorf("%w: renew_difficulty (%v) exceeds difficulty (%v) — renewals are meant to be cheaper than admission", ErrBadDifficulty, c.RenewDifficulty, c.Difficulty)
	}
	if c.Pages != "" {
		for _, f := range []string{"header.html", "footer.html"} {
			if _, err := os.Stat(c.Pages + "/" + f); err != nil {
				return fmt.Errorf("config: pages = %q but %s is missing — create it, or drop `pages` to use the built-in wait page", c.Pages, f)
			}
		}
	}
	// Validate bypass + trusted_proxies by compiling them.
	if _, err := bypass.New(c.Bypass.Paths, c.Bypass.CIDRs, c.TrustedProxies); err != nil {
		return err
	}
	for i := range c.HMACKeys {
		k := &c.HMACKeys[i]
		if k.Kid == "" {
			return fmt.Errorf("%w: hmac_keys[%d] needs a kid", ErrBadKey, i)
		}
		raw, err := decodeB64(k.Key)
		if err != nil || len(raw) < 16 {
			return fmt.Errorf("%w: hmac_keys[%q] must be base64 of at least 16 bytes — generate one with: openssl rand -base64 32", ErrBadKey, k.Kid)
		}
	}
	if len(c.HMACKeys) == 0 {
		var raw [32]byte
		if _, err := rand.Read(raw[:]); err != nil {
			return fmt.Errorf("config: generating hmac key: %w", err)
		}
		c.HMACKeys = []HMACKey{{Kid: "auto", Key: base64.StdEncoding.EncodeToString(raw[:])}}
		c.KeyAutoGenerated = true
	}
	if c.Payments != nil {
		if err := c.Payments.validate(); err != nil {
			return err
		}
	}
	if c.Activity != nil {
		if err := c.Activity.validate(); err != nil {
			return err
		}
	}
	return nil
}

// checkFacilitatorURL validates a facilitator URL under key (a config path for
// error messages). Empty is the caller's concern — for the global key it is an
// error, for a rail it means "inherit".
func checkFacilitatorURL(raw, key string) error {
	u, err := url.Parse(raw)
	if err != nil || u.Host == "" || u.Scheme != "https" && u.Scheme != "http" {
		return fmt.Errorf("config: %s %q is not an http(s) URL", key, raw)
	}
	// Plaintext to anywhere but loopback is refused. The facilitator link
	// carries signed payment authorizations one way and settlement verdicts the
	// other, and the gate serves content on the strength of those verdicts — so
	// an on-path attacker who can forge `{"success": true}` gets paid content
	// for free, indefinitely, without ever paying anyone. Loopback is exempt so
	// a local facilitator and the test suite still work.
	if u.Scheme == "http" && !isLoopbackHost(u.Hostname()) {
		return fmt.Errorf("config: %s %q is plaintext http — "+
			"settlement verdicts decide whether content is served, so a forged "+
			"response over an unencrypted link is free access to paid content. "+
			"Use https (http is allowed only for localhost)", key, raw)
	}
	// The base URL is quoted in logs and error strings, so credentials
	// embedded in it would be copied everywhere those lines go.
	if u.User != nil {
		return fmt.Errorf("config: %s has credentials in the URL — the URL is logged; put them in facilitator_headers instead", key)
	}
	return nil
}

// facilitatorReservedHeaders are owned by the verifier's own requests; a config
// that names one is fighting the protocol, not configuring auth.
var facilitatorReservedHeaders = map[string]bool{
	"Content-Type": true, "Accept": true, "Content-Length": true,
	"Host": true, "Transfer-Encoding": true, "Connection": true,
}

// parseHeaderList turns ["Name: value", ...] into an http.Header, expanding
// ${VAR} from the environment. Only the braced form is recognized — a bare $
// may legitimately appear in a credential. An unset or empty variable is a
// load error: a facilitator that needs an API key and silently doesn't get one
// fails on every settlement instead, which is a worse place to find the typo.
func parseHeaderList(list []string, key string) (http.Header, error) {
	if len(list) == 0 {
		return nil, nil
	}
	h := make(http.Header, len(list))
	for i, entry := range list {
		var unset []string
		expanded := os.Expand(entry, func(v string) string {
			val := os.Getenv(v)
			if val == "" {
				unset = append(unset, v)
			}
			return val
		})
		if len(unset) > 0 {
			return nil, fmt.Errorf("config: %s[%d] references unset environment variable(s) %v — export them before starting", key, i, unset)
		}
		name, value, ok := strings.Cut(expanded, ":")
		name, value = strings.TrimSpace(name), strings.TrimSpace(value)
		if !ok || name == "" || value == "" {
			return nil, fmt.Errorf(`config: %s[%d] is not "Name: value"`, key, i)
		}
		if !isHTTPToken(name) {
			return nil, fmt.Errorf("config: %s[%d] header name %q is not a valid HTTP header name", key, i, name)
		}
		if facilitatorReservedHeaders[http.CanonicalHeaderKey(name)] {
			return nil, fmt.Errorf("config: %s[%d] header %q is owned by the gate's own requests — auth headers only", key, i, name)
		}
		h.Set(name, value)
	}
	return h, nil
}

// isHTTPToken reports whether s is a valid RFC 9110 token (the grammar for a
// header field name).
func isHTTPToken(s string) bool {
	for _, c := range s {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
		case strings.ContainsRune("!#$%&'*+-.^_`|~", c):
		default:
			return false
		}
	}
	return s != ""
}

func (p *Payments) validate() error {
	if p.PayTo == "" {
		return fmt.Errorf("%w — your PUBLIC receiving address; Anteroom never generates one (create yours with: cast wallet new)", ErrNoPayTo)
	}
	if p.Facilitator == "" {
		return errors.New("config: payments.facilitator is required — the x402 facilitator URL your payments settle through")
	}
	if err := checkFacilitatorURL(p.Facilitator, "payments.facilitator"); err != nil {
		return err
	}
	globalHdr, err := parseHeaderList(p.FacilitatorHeaders, "payments.facilitator_headers")
	if err != nil {
		return err
	}
	// pay_to shape. A typo here does not fail loudly at runtime — it advertises
	// a recipient nobody controls, and every payment made against the offer is
	// lost. The gate never generates an address, so checking the one it is given
	// is the only safety there is.
	if err := checkPayTo(p.PayTo, p.Rails, "payments.pay_to"); err != nil {
		return err
	}
	if len(p.Rails) == 0 {
		return fmt.Errorf("config: payments needs at least one [[payments.rails]] — e.g.\n  [[payments.rails]]\n  network = \"eip155:8453\"\n  asset = \"0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913\"\n  asset_name = \"USD Coin\"\n  asset_version = \"2\"")
	}
	seenRail := map[string]bool{}
	for i := range p.Rails {
		rl := &p.Rails[i]
		if rl.Network == "" {
			return fmt.Errorf("config: payments.rails[%d].network is required — a CAIP-2 id, e.g. \"eip155:8453\"", i)
		}
		if !strings.Contains(rl.Network, ":") {
			return fmt.Errorf("config: payments.rails[%d].network %q is not CAIP-2 (want \"namespace:reference\", e.g. \"eip155:72344\")", i, rl.Network)
		}
		if seenRail[rl.Network] {
			return fmt.Errorf("config: duplicate payments.rails network %q", rl.Network)
		}
		seenRail[rl.Network] = true
		if rl.Asset == "" {
			return fmt.Errorf("config: payments.rails[%q].asset is required — the token contract payments arrive in", rl.Network)
		}
		if rl.Decimals == 0 {
			rl.Decimals = 6
		}
		if rl.Decimals < 0 || rl.Decimals > 36 {
			return fmt.Errorf("config: payments.rails[%q].decimals %d outside [1, 36]", rl.Network, rl.Decimals)
		}
		if rl.AssetTransferMethod == "" {
			rl.AssetTransferMethod = "eip3009" // the x402 `exact` default
		}
		if rl.RPCURL != "" {
			if u, err := url.Parse(rl.RPCURL); err != nil || u.Host == "" ||
				u.Scheme != "https" && u.Scheme != "http" {
				return fmt.Errorf("config: payments.rails[%d].rpc_url %q is not an http(s) URL", i, rl.RPCURL)
			}
		}
		if rl.PayTo != "" {
			if err := checkPayTo(rl.PayTo, []Rail{*rl}, fmt.Sprintf("payments.rails[%d].pay_to", i)); err != nil {
				return err
			}
		}
		if rl.Facilitator != "" {
			if err := checkFacilitatorURL(rl.Facilitator, fmt.Sprintf("payments.rails[%d].facilitator", i)); err != nil {
				return err
			}
			rl.FacilitatorHeader, err = parseHeaderList(rl.FacilitatorHeaders, fmt.Sprintf("payments.rails[%d].facilitator_headers", i))
			if err != nil {
				return err
			}
		} else if len(rl.FacilitatorHeaders) > 0 {
			// Headers are credentials for a specific facilitator. Attaching
			// them to an inherited URL would mean a later change to the global
			// facilitator silently re-aims this rail's credential at a new
			// host.
			return fmt.Errorf("config: payments.rails[%d] sets facilitator_headers without facilitator — set payments.rails[%d].facilitator, or move them to payments.facilitator_headers", i, i)
		}
		if !transferMethods[rl.AssetTransferMethod] {
			extra := ""
			if rl.AssetTransferMethod == "erc7710" {
				extra = " (erc7710 is in the spec but no shipped client implements it, so advertising it would produce an offer nothing can pay)"
			}
			return fmt.Errorf("config: payments.rails[%q].asset_transfer_method %q — want \"eip3009\" or \"permit2\"%s", rl.Network, rl.AssetTransferMethod, extra)
		}
		// The EIP-712 domain is required for eip3009, and required for permit2
		// when the token supports EIP-2612 (the common case, including Radius
		// SBC). The reference client throws outright without it, so insist here
		// rather than emitting an unpayable offer.
		if rl.AssetName == "" || rl.AssetVersion == "" {
			return fmt.Errorf("config: payments.rails[%q] needs asset_name and asset_version — the token contract's EIP-712 domain, advertised as extra.name/extra.version; a client cannot sign without them (USDC: \"USD Coin\"/\"2\"; Radius SBC: \"Stable Coin\"/\"1\")", rl.Network)
		}
		if rl.PayTo == "" {
			rl.PayTo = p.PayTo
		}
		// URL and headers inherit as a unit — see the field comment on
		// Rail.Facilitator.
		if rl.Facilitator == "" {
			rl.Facilitator = p.Facilitator
			rl.FacilitatorHeader = globalHdr
		}
	}
	if p.MaxTimeoutSeconds == 0 {
		p.MaxTimeoutSeconds = 300
	}
	if p.MaxTimeoutSeconds < 1 || p.MaxTimeoutSeconds > 3600 {
		return fmt.Errorf("config: payments.max_timeout_seconds %d outside [1, 3600]", p.MaxTimeoutSeconds)
	}
	if len(p.Rules) == 0 {
		return fmt.Errorf("%w — e.g.\n  [[payments.rules]]\n  name = \"site\"\n  paths = [\"/*\"]\n  price = \"$0.01\"", ErrNoRules)
	}
	seen := map[string]bool{}
	for i := range p.Rules {
		r := &p.Rules[i]
		if r.Name == "" {
			return fmt.Errorf("config: payments.rules[%d] needs a name (it becomes the pass scope)", i)
		}
		// The wildcard scope is carried by proof-of-work passes. A rule with
		// that name would mint site-wide paid passes regardless of its paths.
		if r.Name == token.ScopeAll {
			return fmt.Errorf("config: payments.rules[%d]: %q is reserved (it is the wildcard pass scope) — name the rule after what it sells", i, r.Name)
		}
		if seen[r.Name] {
			return fmt.Errorf("config: duplicate payments.rules name %q — names are pass scopes and must be unique", r.Name)
		}
		seen[r.Name] = true
		if len(r.Paths) == 0 {
			return fmt.Errorf("config: payments.rules[%q] needs paths, e.g. [\"/*\"]", r.Name)
		}
		if _, err := bypass.New(r.Paths, nil, nil); err != nil {
			return fmt.Errorf("config: payments.rules[%q]: %w", r.Name, err)
		}
		// One display price, resolved per rail: the same "$0.01" is a different
		// atomic amount on assets with different decimals.
		r.PriceAtomic = make(map[string]*big.Int, len(p.Rails))
		for _, rl := range p.Rails {
			atomic, err := parsePrice(r.Price, rl.Decimals)
			if err != nil {
				return fmt.Errorf("%w: payments.rules[%q].price %q on rail %q: %v", ErrBadPrice, r.Name, r.Price, rl.Network, err)
			}
			r.PriceAtomic[rl.Network] = atomic
		}
		if r.PaidTTL.D() < time.Second {
			return fmt.Errorf("%w: payments.rules[%q].paid_ttl must be at least 1s; zero-length pay-per-request grants cannot be recovered after settlement", ErrBadTTL, r.Name)
		}
	}
	return nil
}

// UpstreamURL normalizes upstream into a URL: bare host:port gets http://.
func (c *Config) UpstreamURL() (*url.URL, error) {
	if path := c.UpstreamSocket(); path != "" {
		// A unix socket has no host, but the reverse proxy still needs a URL to
		// build a request line from. The host is a placeholder that never
		// reaches the wire: the transport dials the socket path instead, and
		// the upstream is told the visitor's Host like any other deployment.
		return &url.URL{Scheme: "http", Host: "unix"}, nil
	}
	s := c.Upstream
	if !strings.Contains(s, "://") {
		s = "http://" + s
	}
	u, err := url.Parse(s)
	if err != nil || u.Host == "" || u.Scheme != "http" && u.Scheme != "https" {
		return nil, fmt.Errorf("config: upstream %q is not host:port, an http(s) URL, "+
			"or unix:/path/to.sock", c.Upstream)
	}
	return u, nil
}

// UpstreamSocket returns the unix socket path when upstream names one, or "".
//
// Application servers bound to a unix socket rather than a port are ordinary —
// gunicorn, puma, uwsgi and php-fpm all default that way in most packaging, and
// nginx reaches them with `proxy_pass http://unix:/run/app.sock`. Without this
// the only way to put the gate in front of such an app is to move it onto a TCP
// port, which is a change to someone else's service to accommodate ours.
//
// Accepted forms: "unix:/run/app.sock" and "unix:///run/app.sock".
func (c *Config) UpstreamSocket() string {
	rest, ok := strings.CutPrefix(c.Upstream, "unix:")
	if !ok {
		return ""
	}
	rest = strings.TrimPrefix(rest, "//")
	if rest == "" || !strings.HasPrefix(rest, "/") {
		return ""
	}
	return rest
}

// Key is decoded HMAC key material shared with the token and challenge keyrings.
type Key struct {
	Kid string
	Key []byte
}

// Keys decodes the configured HMAC keys, first key signs.
func (c *Config) Keys() ([]Key, error) {
	out := make([]Key, 0, len(c.HMACKeys))
	for _, k := range c.HMACKeys {
		raw, err := decodeB64(k.Key)
		if err != nil {
			return nil, fmt.Errorf("%w: %q", ErrBadKey, k.Kid)
		}
		out = append(out, Key{Kid: k.Kid, Key: raw})
	}
	return out, nil
}

func decodeB64(s string) ([]byte, error) {
	for _, enc := range []*base64.Encoding{
		base64.StdEncoding, base64.RawStdEncoding, base64.URLEncoding, base64.RawURLEncoding,
	} {
		if b, err := enc.DecodeString(s); err == nil {
			return b, nil
		}
	}
	return nil, errors.New("not base64")
}

// parsePrice converts a display price like "$0.01" or "0.002" into atomic
// units of an asset with the given decimals. It rejects zero — a rule that
// charges nothing is a misconfiguration, not a free tier (the challenge path
// is the free tier).
func parsePrice(price string, decimals int) (*big.Int, error) {
	if decimals < 0 || decimals > 36 {
		return nil, fmt.Errorf("decimals %d outside [0, 36]", decimals)
	}
	s := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(price), "$"))
	if s == "" {
		return nil, errors.New("empty")
	}
	whole, frac, _ := strings.Cut(s, ".")
	if whole == "" && frac == "" {
		return nil, errors.New("no digits")
	}
	if whole == "" {
		whole = "0"
	}
	for _, r := range whole + frac {
		if r < '0' || r > '9' {
			return nil, fmt.Errorf("unexpected character %q", r)
		}
	}
	if len(frac) > decimals {
		return nil, fmt.Errorf("%d fractional digits but the asset has %d decimals", len(frac), decimals)
	}
	frac += strings.Repeat("0", decimals-len(frac))
	n, ok := new(big.Int).SetString(whole+frac, 10)
	if !ok {
		return nil, errors.New("unparseable number")
	}
	if n.Sign() == 0 {
		return nil, errors.New("price is zero — the free tier is the challenge, not a zero price")
	}
	return n, nil
}

// isLoopbackHost reports whether a host is unambiguously local.
func isLoopbackHost(h string) bool {
	if h == "localhost" {
		return true
	}
	ip := net.ParseIP(h)
	return ip != nil && ip.IsLoopback()
}

// evmAddress matches an EVM address: 0x and forty hex digits.
var evmAddress = regexp.MustCompile(`^0x[0-9a-fA-F]{40}$`)

// checkPayTo validates a receiving address against the rails it will be
// advertised on. Only eip155 rails are checked, because that is the only family
// v0 can settle — the transfer methods are all EVM.
func checkPayTo(addr string, rails []Rail, key string) error {
	if addr == "" {
		return nil // absence is handled by the caller with a better message
	}
	evm := false
	for _, r := range rails {
		if strings.HasPrefix(r.Network, "eip155:") {
			evm = true
		}
	}
	if evm && !evmAddress.MatchString(addr) {
		return fmt.Errorf("config: %s %q is not an EVM address (0x + 40 hex digits) — "+
			"payments advertised on an eip155 rail would name a recipient nobody controls",
			key, addr)
	}
	return nil
}
