package config

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
)

func TestConfigRejectsNonCanonicalKeys(t *testing.T) {
	for _, body := range []string{
		minimal + "Inject = false\n",
		minimal + "inject = true\nInject = false\n",
		minimal + "[Triage]\njson_accept = false\n",
		minimal + "[triage]\nJSON_ACCEPT = false\n",
		minimal + "[[hmac_keys]]\nKid = \"test\"\nkey = \"AAAAAAAAAAAAAAAAAAAAAA==\"\n",
	} {
		t.Run(body, func(t *testing.T) {
			_, err := Load(write(t, body))
			if err == nil || !strings.Contains(err.Error(), "unknown key") {
				t.Fatalf("non-canonical key must fail explicitly: %v", err)
			}
		})
	}
}

func TestConfigKeyErrorsNamePathAndMigration(t *testing.T) {
	for _, tc := range []struct {
		name, body, path, hint string
	}{
		{"root typo", "upstrem = \"SECRET\"\n", "upstrem", "table placement"},
		{"empty unknown table", "[triage.typo]\n", "triage.typo", "table placement"},
		{"misplaced key", "[bypass]\njson_accept = true\n", "bypass.json_accept", "table placement"},
		{"inline typo", "triage = { json_accept = true, typo = false }\n", "triage.typo", "table placement"},
		{"quoted dotted key", "\"triage.json_accept\" = true\n", "triage.json_accept", "table placement"},
		{"root case", "Inject = false\n", "Inject", "use \"inject\""},
		{"nested case", "[triage]\nJSON_ACCEPT = false\n", "triage.JSON_ACCEPT", "use \"triage.json_accept\""},
		{"crawler migration", "[bypass]\ncrawlers = [\"googlebot\"]\n", "bypass.crawlers", "bypass.verified_crawlers"},
		{"v1 migration", "[[payments.rails]]\nv1_network = \"base\"\n", "payments.rails.v1_network", "CAIP-2"},
		{"grant migration", "[[payments.rules]]\ngrant = \"session\"\n", "payments.rules.grant", "request-count grants are unsupported"},
		{"scheme migration", "[[payments.rules]]\nscheme = \"exact\"\n", "payments.rules.scheme", "exact is the only supported"},
		{"challenge migration", "[[payments.rules]]\nchallenge = \"pow-sha256\"\n", "payments.rules.challenge", "top-level difficulty"},
		{"internal field", "KeyAutoGenerated = true\n", "KeyAutoGenerated", "table placement"},
		{"array member", "[[payments.rules]]\nname = \"first\"\n[[payments.rules]]\ntypo = true\n", "payments.rules.typo", "table placement"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := write(t, minimal+tc.body)
			_, err := Load(path)
			if err == nil {
				t.Fatal("accepted invalid config")
			}
			for _, want := range []string{path, "unknown key", tc.path, tc.hint} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("error %q lacks %q", err, want)
				}
			}
			if strings.Contains(err.Error(), "SECRET") {
				t.Error("unknown-key error exposed the configured value")
			}
		})
	}
}

func TestConfigReportsAllUnknownPaths(t *testing.T) {
	_, err := Load(write(t, minimal+"typo = true\n[bypass]\ncrawlers = []\n[triage]\nother = false\n"))
	if err == nil {
		t.Fatal("accepted invalid config")
	}
	for _, key := range []string{"typo", "bypass.crawlers", "triage.other"} {
		if !strings.Contains(err.Error(), key) {
			t.Errorf("error %q lacks %q", err, key)
		}
	}
}

func TestConfigAcceptsCanonicalKeyForms(t *testing.T) {
	for _, body := range []string{
		minimal + "triage.json_accept = false\n",
		minimal + "triage = { json_accept = false, ok_body_agents = [] }\n",
		minimal + "[\"triage\"]\n\"json_accept\" = false\n",
	} {
		cfg, err := Load(write(t, body))
		if err != nil {
			t.Fatal(err)
		}
		if cfg.Triage.JSONAccept {
			t.Fatal("explicit false was not preserved")
		}
	}
}

// Check every shipped TOML's schema. Example values intentionally include a
// placeholder wallet and container-only filesystem paths, so this test does
// not claim they are deployable without editing their values.
func TestShippedConfigSchemas(t *testing.T) {
	for _, path := range []string{
		"anteroom.example.toml",
		"docker/anteroom.default.toml",
		"examples/caddy-tls/anteroom.toml",
		"examples/anteroomized/anteroom.toml",
	} {
		t.Run(path, func(t *testing.T) {
			cfg := defaults()
			meta, err := toml.DecodeFile(filepath.Join("../..", path), &cfg)
			if err != nil {
				t.Fatal(err)
			}
			if err := validateConfigKeys(meta); err != nil {
				t.Fatal(err)
			}
			if keys := meta.Undecoded(); len(keys) > 0 {
				t.Fatalf("undecoded keys: %v", keys)
			}
		})
	}
}

func TestConfigRejectsNonFiniteDifficulty(t *testing.T) {
	for _, key := range []string{"difficulty", "renew_difficulty"} {
		for _, value := range []string{"nan", "+nan", "-nan", "inf", "+inf", "-inf"} {
			t.Run(key+"="+value, func(t *testing.T) {
				_, err := Load(write(t, minimal+key+" = "+value+"\n"))
				if err == nil || !strings.Contains(err.Error(), key) {
					t.Fatalf("non-finite difficulty must fail explicitly: %v", err)
				}
			})
		}
	}
}
